[package]
name = "nexus-3"
version = "0.1.0"
edition = "2024"

[dependencies]
nexus-sdk = { git = "https://github.com/nexus-xyz/nexus-zkvm.git", tag = "0.3.1", version = "0.3.1" }
utils = { path = "../utils" }

[workspace]
members = [
    "src/fibonacci-guest",
    "src/sha2-guest",
]


