[package]
name = "ethblock-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
# alloy-sol-types = { workspace = true }
# anyhow = "1.0.95"
# revm = {version = "19.5.0", default-features = false, features = ["serde"]}
revm = {git = "https://github.com/bluealloy/revm", features = ["serde"]}
revm-database = {git = "https://github.com/bluealloy/revm", features = ["serde", "alloydb"]}
revm-database-interface = {git = "https://github.com/bluealloy/revm", features = ["serde", "asyncdb"]}
revm-inspector = {git = "https://github.com/bluealloy/revm", features = ["serde", "serde-json", "std" ]}

# serde = "1.0.217"
# serde_json = "1.0.138"
# bincode = "1.3.3"
# # models = { git = "https://github.com/zkMIPS/powdr-revme", branch = "continuations", package = "models" }
# k256 = { version = "=0.13.3", features = [
#   # "arithmetic",
#   # "serde",
#   # "expose-field",
#   # "std",
#   "ecdsa",
# ], default-features = false }

# alloy-provider = { git = "https://github.com/alloy-rs/alloy", version = "0.11.1" }
# alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", version = "0.11.1" }
# alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", version = "0.11.1" }


# url = "2.5.0"
# tokio = {version = "1.43.0", features = ["rt-multi-thread", "macros"] }
# reqwest = "0.12.4"

tokio = { version = "1.43", features = ["rt-multi-thread", "macros"] }

# alloy
alloy-eips = "0.9.2"
alloy-provider = "0.9.2"
alloy-consensus = "0.9.2"

# progress bar
indicatif = "0.17"

# mics
anyhow = "1.0.89"
