[package]
name = "ethblock-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
# revm
revm = {git = "https://github.com/bluealloy/revm", features = ["serde"]}
revm-database = {git = "https://github.com/bluealloy/revm", features = ["serde", "alloydb"]}
revm-database-interface = {git = "https://github.com/bluealloy/revm", features = ["serde", "asyncdb"]}
revm-inspector = {git = "https://github.com/bluealloy/revm", features = ["serde", "serde-json", "std" ]}

# util
ethblock-utils = {path = "../utils"}

# serialize
bincode = "1.3.3"
serde = "1.0.217"

tokio = { version = "1.43", features = ["rt-multi-thread", "macros"] }

# alloy
alloy-eips = "0.9.2"
alloy-provider = "0.9.2"
alloy-consensus = "0.9.2"

# progress bar
indicatif = "0.17"

# mics
anyhow = "1.0.89"
