[package]
name = "tendermint"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm-zkvm = { workspace= true }
tendermint-light-client-verifier = { version = "0.35.0", default-features = false, features = [
  "rust-crypto",
] }
serde_cbor = "0.11.2"
