[package]
name = "risc0-benchmark-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "2.0.1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
