[workspace]
members = [
  "fibonacci",
  "sha2",
  "sha3",
  "ecdsa",
  "transfer-eth",
]
resolver = "2"

[workspace.dependencies]
zkm-zkvm = { git = "https://github.com/zkMIPS/zkMIPS.git" }
guests = { path = "../../guests" }

[workspace.package]
version = "1.1.0"
edition = "2021"
