[package]
name = "prover"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { workspace = true }
bincode = "1.3.3"
ecdsa-lib = { path = "../lib" }
serde = { workspace = true }
utils = { path = "../../../utils" }
hex = "0.4.3"
k256 = { version = "=0.13.3", features = [
  "arithmetic",
  "serde",
  "expose-field",
  "std",
  "ecdsa",
], default-features = false }